services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3002:80" # Map host port 3002 to container port 80 (Nginx default)
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 800M

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001 (Express app)
    environment:
      NODE_ENV: production # Set environment to production
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1200M

networks:
  app-network:
    driver: bridge 