services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_data:/tmp/uploads
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - PORT=8000
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - STORAGE_PATH=/tmp/uploads
      - MAX_FILE_SIZE=2147483648
      - FILE_RETENTION_HOURS=24
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: ./backend
    command: python -m app.worker
    volumes:
      - ./backend:/app
      - uploads_data:/tmp/uploads
    deploy:
      resources:
        limits:
          memory: 1536M
    environment:
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - STORAGE_PATH=/tmp/uploads
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_RETENTION_HOURS=24
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  uploads_data:
